### ISSUE TITLE
안과 가보기

### ISSUE THREAD

**Issue by nulta** [Hoto-Cocoa/Real-Life#35]
너무 미루면 어떻게 될지 모름

**Comment by Hoto-Cocoa** [comment]
현재 문제
1. 자고 일어나거나 하면 오른쪽 눈(안구)에 심한 통증이 발생 (안압이 높아지는 느낌?) -> 10~30분 정도는 눈이 아파서 아무것도 하지 못할 정도, 계속해서 눈을 누르고 있거나 하게 됨
2. 간헐적으로 양쪽 눈으로 시야를 볼 때 오른쪽 눈이 뭔가 문제를 일으킴 (오른쪽 눈을 가려버리는게 훨씬 앞이 잘 보이는 수준)

오른쪽 눈에 뭔가 문제가 생긴 것 같은데 어떤 문제인지 잘 모르겠지만 문제가 심상치는 않기에 빠른 시일 내에 안과 방문이 필요할 것으로 생각

**Comment by nulta** [comment]
- 만약 심각한 안과질환이라면 시간이 얼마나 남아있는지 알 수 없으니 최대한 빨리 가보는 게 좋을 듯함
- 운전하다가 뭔가 잘못되면 정말로 큰일날 수도 있으니 최대한 빨리 가보는 게 좋을 듯함

**Comment by nulta** [comment]
👀

**Comment by Hoto-Cocoa** [comment]
엣큥

**Comment by SuFl3770** [comment]
빨리 안과 가라고

**Comment by Hoto-Cocoa** [comment]
검은자에 상처가 났다고 함

안약 받음

**Comment by Hoto-Cocoa** [comment]
다음주 화~수에 경과 관찰을 위해 방문 필요
