### ISSUE TITLE
타이어 교체

### ISSUE THREAD

**Issue by Hoto-Cocoa** [Hoto-Cocoa/Real-Life#40]
ㅃㄹ

타이어가 슬릭이 되게 생김

**Comment by ltlapy** [comment]
그 뒤로 아직 안 바꾸셨던 거에요!?

**Comment by Hoto-Cocoa** [comment]
> 그 뒤로 아직 안 바꾸셨던 거에요!?

시간이 없었어요 으악

**Comment by Hoto-Cocoa** [comment]
![image](https://github.com/user-attachments/assets/d8111381-9ae4-4e31-ac8f-72d2b60d7394)

**Comment by Hoto-Cocoa** [comment]
#41 일정이랑 겹쳐서 하루 미룸

**Comment by ltlapy** [comment]
https://hoto.moe/notes/9wn195nrhq
🚀🚀🚀

**Comment by Hoto-Cocoa** [comment]
완료
