### ISSUE TITLE
치과 스케일링 받기

### ISSUE THREAD

**Issue by asteriskyg** [Hoto-Cocoa/Real-Life#5]
주기적인 스케일링을 통해 구강 건강을 유지할 수 있습니다. 1년에 한 번 국민건강보험 적용을 받아 저렴하게 시술을 받을 수 있습니다. 치과 선생님이 기뻐하실 치아 상태이니 방문을 권장드립니다. 감사합니다.

**Comment by Hoto-Cocoa** [comment]
오늘이나 다음 주 중으로 진행 예정

**Comment by Hoto-Cocoa** [comment]
제 처참한 치아 상태를 돌아 볼 수 있었습니다

**Comment by ltlapy** [comment]
> 주기적인 스케일링을 통해 구강 건강을 유지할 수 있습니다. **1년에 한 번** 국민건강보험 적용을 받아 저렴하게 시술을 받을 수 있습니다.
